# Generated by Django 4.1.5 on 2023-06-30 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountDetailModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.IntegerField()),
                ('balance', models.IntegerField()),
                ('account_type', models.CharField(choices=[('Savings', 'Savings'), ('Credit', 'Credit')], max_length=40)),
            ],
        ),
    ]
