# Generated by Django 4.1.5 on 2023-06-30 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('address', models.CharField(max_length=150)),
                ('ph_num', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('account', models.ManyToManyField(to='bankapp.accountdetailmodel')),
            ],
        ),
    ]
