# Generated by Django 4.1.5 on 2023-06-30 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0002_customermodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customermodel',
            old_name='account',
            new_name='accounts',
        ),
    ]
